### ISSUE TITLE
warning in

### ISSUE THREAD

**Issue by Dawood-Li** [chenjunfu2/CPP_Range#2]

**Comment by Dawood-Li** [comment]
in file Range.hpp
in line 12: 
throw "Step is zero!";//错误值异常

this exception types const char* may not excute it well.
because the code must capture it use "catch block typed const char*" by user itself.
if not, the program will be terminate, but not display anything.

for example:

try {
    for (auto i : Range<int>(0)) {  cout << i << endl; }
    }  catch(std::exception &err) { // default exception type
        cerr << err.what() << endl;
    } catch(const char* err) { // if not capture this type, the program will error!!! user must to capture it!!!
        cerr << err << endl;
    } 

suggest method:

    try {
        throw std::invalid_argument("Step is zero!");
    } catch(std::invalid_argument &err) {
        cerr << err.what() << endl;
    }

**Comment by chenjunfu2** [comment]
感谢建议，已修改代码，马上上传
